modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL="https://github.com/Mrbysco/ConstructionSticks/issues"
license = "MIT License"

[[mods]]
modId="constructionstick"
version="${file.jarVersion}"
displayName="Construction Sticks"
displayURL="https://github.com/Mrbysco/ConstructionSticks"
authors="Mrbysco, ShyNieke"
credits="ThetaDev for creating Construction Wand"
description='''
Construction Sticks make building easier!

With a Construction Sticks you can place multiple blocks (up to 1024) at once, extending your build on the side you're
facing. If that's not enough: you can upgrade your stick with additional cores, allowing you to place a block
behind the block you are facing, conjure blocks in mid air or destroy lots of blocks very fast.
'''
[[dependencies.constructionstick]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.constructionstick]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
